In [2]:
from numpy import *

def createDataSet():
    group=array([[1.1,1.2],[0.99,1.123],[0.11,0.01],[0.0,0.0]])
    labels=['A','A','B','B']
    return group,labels


In [3]:
G,L=createDataSet()
print(G)
print(L)
print(G.shape[0])#行数, shape[1]列数
M=tile([0.2,0.3],(4,1))#以[0.2,0.3]为数据，生成4行1列的矩阵
print(M)
M=M-G
print(M**2)#计算矩阵每个元素的平方
print((M**2).sum(axis=1))#计算每一行元素的和
M=(M**2).sum(axis=1)
print(M.argsort())#排序,M[2],M[3],M[1],M[0]
D={'A':3,'B':2,"C":23}
print(D.get('A',0))#得到键'A'对应的值，不存在就返回0
sortedD=sorted(D.items(), key=lambda d:d[1], reverse=True)#通过key指定按照值排序，先大
print(sortedD)
sortedD=sorted(D.items(), key=lambda d:d[0], reverse=True)#通过key指定按照键排序
print(sortedD)
mt=zeros((10,3))#10行3列的0
print(mt)


[[ 1.1    1.2  ]
 [ 0.99   1.123]
 [ 0.11   0.01 ]
 [ 0.     0.   ]]
['A', 'A', 'B', 'B']
4
[[ 0.2  0.3]
 [ 0.2  0.3]
 [ 0.2  0.3]
 [ 0.2  0.3]]
[[ 0.81      0.81    ]
 [ 0.6241    0.677329]
 [ 0.0081    0.0841  ]
 [ 0.04      0.09    ]]
[ 1.62      1.301429  0.0922    0.13    ]
[2 3 1 0]
3
[('C', 23), ('A', 3), ('B', 2)]
[('C', 23), ('B', 2), ('A', 3)]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [4]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]#shape[0] number of rows, shape[1] number of columns
    diffMat=tile(inX,(dataSetSize,1)) - dataSet
    sqDiffMat=diffMat**2
    sqDist=sqDiffMat.sum(axis=1)
    dist=sqDist**0.5
    sortedDistIndicies=dist.argsort()
    
    classCount={}
    for i in range(k):
        voteIlabel=labels[sortedDistIndicies[i]]
        classCount[voteIlabel]=classCount.get(voteIlabel,0)+1
    
    sortedClassCount=sorted(classCount.items(),key=lambda d:d[1],reverse=True)
    return sortedClassCount[0][0]

In [5]:
print(classify0([0.21,0.23], G, L, 3))

B


In [6]:
fr = open('datingTestSet.txt')
line=fr.readline()
line=line.strip()
listFromLine=line.split('\t')
mat=zeros((2,3))
mat[0,:]=listFromLine[0:3]
print(listFromLine[0:3])

['40920', '8.326976', '0.953952']


In [7]:
def file2matrix(filename):
    fr = open(filename)
    numberOfLines=len(fr.readlines())
    retMat=zeros((numberOfLines,3))
    classLabelVector=[]
    fr = open(filename,'r',encoding='utf-8')
    for i,line in enumerate(fr.readlines()):
        line=line.strip()
        listFromLine=line.split('\t')
        retMat[i,:]=listFromLine[0:3]
        classLabelVector.append((listFromLine[-1]))
    return retMat,classLabelVector

datingDataMat,datingLabels=file2matrix('datingTestSet.txt')
print(datingDataMat[0:30,:])
print(datingLabels[0:20])

[[  4.09200000e+04   8.32697600e+00   9.53952000e-01]
 [  1.44880000e+04   7.15346900e+00   1.67390400e+00]
 [  2.60520000e+04   1.44187100e+00   8.05124000e-01]
 [  7.51360000e+04   1.31473940e+01   4.28964000e-01]
 [  3.83440000e+04   1.66978800e+00   1.34296000e-01]
 [  7.29930000e+04   1.01417400e+01   1.03295500e+00]
 [  3.59480000e+04   6.83079200e+00   1.21319200e+00]
 [  4.26660000e+04   1.32763690e+01   5.43880000e-01]
 [  6.74970000e+04   8.63157700e+00   7.49278000e-01]
 [  3.54830000e+04   1.22731690e+01   1.50805300e+00]
 [  5.02420000e+04   3.72349800e+00   8.31917000e-01]
 [  6.32750000e+04   8.38587900e+00   1.66948500e+00]
 [  5.56900000e+03   4.87543500e+00   7.28658000e-01]
 [  5.10520000e+04   4.68009800e+00   6.25224000e-01]
 [  7.73720000e+04   1.52995700e+01   3.31351000e-01]
 [  4.36730000e+04   1.88946100e+00   1.91283000e-01]
 [  6.13640000e+04   7.51675400e+00   1.26916400e+00]
 [  6.96730000e+04   1.42391950e+01   2.61333000e-01]
 [  1.56690000e+04   0.00000

In [8]:
mat=[[1,2,3],
    [4,5,6]]
mat=array(mat)#转化为矩阵才可以用min,max
minVals=mat.min(0)#得到每一列的最小值, min(1)得到每一行的最小值
print(minVals)

[1 2 3]


In [9]:
def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges=maxVals-minVals
    mormDataSet=zeros(shape(dataSet))
    m=dataSet.shape[0]
    normDataSet=dataSet-tile(minVals,(m,1))
    normDataSet=normDataSet/tile(ranges,(m,1))
    return normDataSet,ranges,minVals
normMat,ranges,minVals=autoNorm(datingDataMat)
normMat

array([[ 0.44832535,  0.39805139,  0.56233353],
       [ 0.15873259,  0.34195467,  0.98724416],
       [ 0.28542943,  0.06892523,  0.47449629],
       ..., 
       [ 0.29115949,  0.50910294,  0.51079493],
       [ 0.52711097,  0.43665451,  0.4290048 ],
       [ 0.47940793,  0.3768091 ,  0.78571804]])

In [19]:
ranges

array([  9.12730000e+04,   2.09193490e+01,   1.69436100e+00])

In [20]:
minVals

array([ 0.      ,  0.      ,  0.001156])

In [10]:
def datingTest():
    hoRatio=0.10
    datingDataMat,datingLabels=file2matrix('datingTestSet.txt')
    normMat, ranges, minVals=autoNorm(datingDataMat)
    m=normMat.shape[0]
    numTestVecs=int(m*hoRatio)
    errorCount=0.0
    for i in range(numTestVecs):
        classifierResult=classify0(normMat[i,:],normMat[numTestVecs:m,:],\
                                 datingLabels[numTestVecs:m],3)
        print("%dth test result %s, the real answer is %s" %\
              (i,classifierResult,datingLabels[i]))
        if(classifierResult!=datingLabels[i]):
            errorCount+=1.0
    print ("the total error rate is %f" % (errorCount/float(numTestVecs)))
datingTest()

0th test result largeDoses, the real answer is largeDoses
1th test result smallDoses, the real answer is smallDoses
2th test result didntLike, the real answer is didntLike
3th test result didntLike, the real answer is didntLike
4th test result didntLike, the real answer is didntLike
5th test result didntLike, the real answer is didntLike
6th test result largeDoses, the real answer is largeDoses
7th test result largeDoses, the real answer is largeDoses
8th test result didntLike, the real answer is didntLike
9th test result largeDoses, the real answer is largeDoses
10th test result didntLike, the real answer is didntLike
11th test result didntLike, the real answer is didntLike
12th test result smallDoses, the real answer is smallDoses
13th test result didntLike, the real answer is didntLike
14th test result didntLike, the real answer is didntLike
15th test result didntLike, the real answer is didntLike
16th test result didntLike, the real answer is didntLike
17th test result didntLike, t

In [11]:
def classifyPerson():
    percentT=float(input(\
                            "percentage of time spent playing video games? "))
    ffMiles=float(input(\
                           "frequent flier miles earned per years? "))
    iceCream=float(input(\
                            "liters of ice cream consumed per years? "))
    datingDataMat,datingLabels=file2matrix('datingTestSet.txt')
    normMat,ranges,minVals=autoNorm(datingDataMat)
    inArr=array([ffMiles,percentT,iceCream])
    result=classify0((inArr-minVals)/ranges,\
                    normMat,datingLabels,3)
    print(result)
classifyPerson()


percentage of time spent playing video games? 10
frequent flier miles earned per years? 10000
liters of ice cream consumed per years? 0.5
smallDoses


In [39]:
a=zeros((2,4))
print(a[0,0])#表示第一行第一列的元素
print(a[0])#表示第一行的元素
a[:,0]#表示第一列的元素

0.0


array([ 0.,  0.])

In [12]:
def img2vec(filename):
    retVec=zeros((1,1024))
    fr=open(filename,'r',encoding='utf-8')
    for i in range(32):
        lineStr=fr.readline()
        for j in range(32):
            retVec[0,32*i+j]=int(lineStr[j])
    return retVec
testVec=img2vec('testDigits/0_13.txt')
testVec[0,0:30]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [17]:
from os import listdir

def handwritingClassTest():
    hwLabels=[]
    trainingFileList=listdir('trainingDigits')
    m=len(trainingFileList)
    trainingMat=zeros((m,1024))
    for i in range(m):
        fileNameStr=trainingFileList[i]
        fileStr=fileNameStr.split('.')[0]
        classNumStr=int(fileStr.split('_')[0])
        hwLabels.append(classNumStr)
        trainingMat[i,:]=img2vec('trainingDigits/%s' % fileNameStr)
    testFileList=listdir('testDigits')
    errorCount=0.0
    mTest=len(testFileList)
    for i in range(mTest):
        fileNameStr=testFileList[i]
        fileStr=fileNameStr.split('.')[0]
        classNumStr=int(fileStr.split('_')[0])
        vecUnderTest=img2vec('testDigits/%s' % fileNameStr)
        classifierResult=classify0(vecUnderTest,
                                  trainingMat,hwLabels,3)
        print("%dth test result %s, the real answer is %s" %\
              (i,classifierResult,classNumStr))
        if(classifierResult!=classNumStr):
            errorCount+=1.0
    print ("the total error rate is %f" % (errorCount/float(mTest))) 
handwritingClassTest()

0th test result 0, the real answer is 0
1th test result 0, the real answer is 0
2th test result 0, the real answer is 0
3th test result 0, the real answer is 0
4th test result 0, the real answer is 0
5th test result 0, the real answer is 0
6th test result 0, the real answer is 0
7th test result 0, the real answer is 0
8th test result 0, the real answer is 0
9th test result 0, the real answer is 0
10th test result 0, the real answer is 0
11th test result 0, the real answer is 0
12th test result 0, the real answer is 0
13th test result 0, the real answer is 0
14th test result 0, the real answer is 0
15th test result 0, the real answer is 0
16th test result 0, the real answer is 0
17th test result 0, the real answer is 0
18th test result 0, the real answer is 0
19th test result 0, the real answer is 0
20th test result 0, the real answer is 0
21th test result 0, the real answer is 0
22th test result 0, the real answer is 0
23th test result 0, the real answer is 0
24th test result 0, the re

204th test result 2, the real answer is 2
205th test result 2, the real answer is 2
206th test result 2, the real answer is 2
207th test result 2, the real answer is 2
208th test result 2, the real answer is 2
209th test result 2, the real answer is 2
210th test result 2, the real answer is 2
211th test result 2, the real answer is 2
212th test result 2, the real answer is 2
213th test result 2, the real answer is 2
214th test result 2, the real answer is 2
215th test result 2, the real answer is 2
216th test result 2, the real answer is 2
217th test result 2, the real answer is 2
218th test result 2, the real answer is 2
219th test result 2, the real answer is 2
220th test result 2, the real answer is 2
221th test result 2, the real answer is 2
222th test result 2, the real answer is 2
223th test result 2, the real answer is 2
224th test result 2, the real answer is 2
225th test result 2, the real answer is 2
226th test result 2, the real answer is 2
227th test result 2, the real answ

400th test result 4, the real answer is 4
401th test result 4, the real answer is 4
402th test result 4, the real answer is 4
403th test result 4, the real answer is 4
404th test result 4, the real answer is 4
405th test result 4, the real answer is 4
406th test result 4, the real answer is 4
407th test result 4, the real answer is 4
408th test result 4, the real answer is 4
409th test result 4, the real answer is 4
410th test result 4, the real answer is 4
411th test result 4, the real answer is 4
412th test result 4, the real answer is 4
413th test result 4, the real answer is 4
414th test result 4, the real answer is 4
415th test result 4, the real answer is 4
416th test result 4, the real answer is 4
417th test result 4, the real answer is 4
418th test result 4, the real answer is 4
419th test result 4, the real answer is 4
420th test result 4, the real answer is 4
421th test result 4, the real answer is 4
422th test result 4, the real answer is 4
423th test result 4, the real answ

596th test result 6, the real answer is 6
597th test result 6, the real answer is 6
598th test result 6, the real answer is 6
599th test result 6, the real answer is 6
600th test result 6, the real answer is 6
601th test result 6, the real answer is 6
602th test result 6, the real answer is 6
603th test result 6, the real answer is 6
604th test result 6, the real answer is 6
605th test result 6, the real answer is 6
606th test result 6, the real answer is 6
607th test result 6, the real answer is 6
608th test result 6, the real answer is 6
609th test result 6, the real answer is 6
610th test result 6, the real answer is 6
611th test result 6, the real answer is 6
612th test result 6, the real answer is 6
613th test result 6, the real answer is 6
614th test result 6, the real answer is 6
615th test result 6, the real answer is 6
616th test result 6, the real answer is 6
617th test result 6, the real answer is 6
618th test result 6, the real answer is 6
619th test result 6, the real answ

793th test result 8, the real answer is 8
794th test result 8, the real answer is 8
795th test result 8, the real answer is 8
796th test result 1, the real answer is 8
797th test result 8, the real answer is 8
798th test result 8, the real answer is 8
799th test result 8, the real answer is 8
800th test result 8, the real answer is 8
801th test result 8, the real answer is 8
802th test result 8, the real answer is 8
803th test result 8, the real answer is 8
804th test result 8, the real answer is 8
805th test result 8, the real answer is 8
806th test result 1, the real answer is 8
807th test result 8, the real answer is 8
808th test result 8, the real answer is 8
809th test result 8, the real answer is 8
810th test result 8, the real answer is 8
811th test result 8, the real answer is 8
812th test result 8, the real answer is 8
813th test result 8, the real answer is 8
814th test result 8, the real answer is 8
815th test result 8, the real answer is 8
816th test result 8, the real answ